### ISSUE TITLE
Screenreader

### ISSUE THREAD

**Issue by RayanSp** [RubenErhardt/all-human-wcag-audit#1]
Je zegt dat de screenreader niet consistent is. Soms hoor je wel wat die zegt en soms niet, maar wat is hiervoor de oplossing. 
Alt toevoegen? 

Probeer hier nog iets over te typen.

**Comment by RubenErhardt** [comment]
Ik heb er nu bijgezet, dat er betere unieke benamingen moeten komen, door bijvoorbeeld een alt toe te voegen. Dit zou een oplossing kunnen zijn voor de inconsistentie op de website met gebruik van een screenreader.
